### ISSUE TITLE
Proposition to switch the language of the Issues to English.

### ISSUE THREAD

**Issue by andrrsin** [Arquisoft/lomapSpec#2]
Due to this Repository being a public repo where sometimes random people may appear as it has happened in my project already, I propose to from now on speak in English in the issues.

**Comment by Omitg24** [comment]
Keeping in mind what Labra said on Friday, I also think it would be better if we all change to speak English in the following issues.

**Comment by alvaroglezeri** [comment]
Agreed! I will translate my contributions to english now :)
