### ISSUE TITLE
LoMap marker categories

### ISSUE THREAD

**Issue by Omitg24** [Arquisoft/lomapSpec#9]
# Categories for the markers of our LoMap apps 
<p align="justify">
Hello everybody, after talking with some of our teammates, such as @gonzalo-rr, I thought that we should define a concrete number of categories (and the values we'll save) in our PODs, so when we change from one app to another, the filters do still work.
</p>

<p align="justify">
As for now, in my team we have defined a total of <em>11</em> categories and one for the rest, called others, so in case anyone has the functionality which gives the user the possibility of adding new categories, the marker will still be shown after using the filters, the categories we have defined are:
</p>
<ul>
       <li>Bars.</li>
       <li>Restaurants.</li>
       <li>Shops.</li>
       <li>Supermarkets.</li>
       <li>Hotels.</li>
       <li>Cinemas.</li>
       <li>Academic institutions.</li>
       <li>Public institutions.</li>
       <li>Sports clubs.</li>
       <li>Museums.</li>
       <li>Parks.</li>
       <li>Others.</li>
</ul>

<p align="justify">
Right now, we just have this (which I think are a lot), but it could be better if we decide how to go through this and everyone can have the same number of categories and store the same value in our PODs.
</p>

</p align="justify">
If you have any better idea or you think of another category we should be adding, I'd be thankful if you share it and we can have this functionality finished as soon as its possible.
</p>

- <a href="mailto:UO281847@uniovi.es">Omar Teixeira</a>.

**Comment by gitblanc** [comment]
I like those categories, but in the user pod I think that must be stored in singular and camelcase like:
- bar
- restaurant
- shop
- supermarket
- hotel
- cinema
- academicInstitution
- publicInstitution
- sportsClub
- museum
- park
- other

And I also woulds add a category called `landscape`

Tell me what you think

**Comment by Omitg24** [comment]
Great @gitblanc! I also think we should add categories, such as the one you suggested.

- <a href="mailto:UO281847@uniovi.es">Omar Teixeira</a>.

**Comment by uo282422** [comment]
Hello,  the ones you have proposed seem very correct to me.
I would also add:
- clinic/hospital
-policeStation
-transportCentre (including with this airports, stations...)
-entertainment

Another issue would be whether we store the category names somewhere in the pod itself or commit to using those and retrieving them normally from point. 

It is also important to decide if the categories are going to be fixed or are going to have modifications, in order to be able to put certain filters and not have to do them dynamically each time points are loaded (checking each load to see what categories there are and creating accordingly )

- @uo282422

**Comment by DavidGonzalezFernandez** [comment]
> It is also important to decide if the categories are going to be fixed or are going to have modifications, in order to be able to put certain filters and not have to do them dynamically each time points are loaded (checking each load to see what categories there are and creating accordingly )

@uo282422 I believe that categories should be decided, fixed and, at least in the short term, not modified. That being said, I don't see why adding or removing categories would be a problem.

---

> Another issue would be whether we store the category names somewhere in the pod itself or commit to using those and retrieving them normally from point.

Regarding this @uo282422 comment, I understand that the allowed categories are part of the specification, not the user's data, so it doesn't make sense to store them in the user's POD. Additionally, if we were to add it to the user's POD, the user could delete or modify the data. I came up with two solutions, each with their own pros and cons:
- Agree to use certain categories and hardcode them into the application's code. This is simple, but violates the open-closed principle if we want to modify the categories of the common specification.
- The other option is to create a single source of truth that everyone can consult to access the information. This option allows making changes to the categories to be transparent to the specific implementation of each group. One possible option would be to have a publicly readable POD, but without write permission.

**Comment by gitblanc** [comment]
I think that we can set a predefined categories (the ones we talked about @Omitg24 and me before). So if our app doesn't detect the new category that your app added would be set as `other`. It's not a big problem I think. In my case if my app doesn't detect the categories that I contemplate, they treat them like `other`.

**Comment by uo282422** [comment]
> I think that we can set a predefined categories (the ones we talked about @Omitg24 and me before). So if our app doesn't detect the new category that your app added would be set as `other`. It's not a big problem I think. In my case if my app doesn't detect the categories that I contemplate, they treat them like `other`.

Ok, I see it very correct. How about adding those categories I've said before (clinic, policeStation, transportCentre, entertainment)? They are very common places on a map, wherever you go.

-@uo282422

**Comment by gitblanc** [comment]
ok, I'm gonna set the common categories top recognize:

**Comment by gitblanc** [comment]
# OFFICIAL CATEGORIES recognised by LoMap
- bar
- restaurant
- shop
- supermarket
- hotel
- cinema
- academicInstitution
- publicInstitution
- sportsClub
- museum
- park
- landscape
- hospital
- policeStation
- transportCentre
- entertaiment
- other (any other category)
